version: '3.8'
services:
  backend:
    command: gunicorn config.wsgi
    image: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: skyskill_backend_prod
    env_file:
      - ./backend/.env
    ports:
      - 5000:5000
    #networks:
    #  - skyskill-net
  frontend:
    command: serve -s build
    #image: tieje/skyskill_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: skyskill_frontend_prod
    ports:
      - 3000:3000
    #networks:
    #  - skyskill-net
#networks:
 # skyskill-net:
 #   driver: overlay
