version: '3.8'

services:
  backend:
    #command: python3 manage.py runserver 0.0.0.0:8000 --verbosity 3
    command: sh setup.sh
    image: tieje/skyskill_backend
    container_name: skyskill_backend_prod
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    # Only need this for local development
    #env_file:
    #  - ./backend/.env
    ports:
      - 5000:5000
    networks:
      - skyskill-net
  frontend:
    command: serve -s build
    image: tieje/skyskill_frontend
    container_name: skyskill_frontend_prod
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - 3000:3000
    networks:
      - skyskill-net
networks:
  skyskill-net:
    driver: overlay
