FROM python:3.10.4
RUN apt-get update
WORKDIR /backend
COPY Pipfile Pipfile.lock /backend/
RUN /usr/local/bin/python -m pip install --upgrade pip\
    && pip install pipenv\
    && pipenv install --system
COPY . /backend 
# CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
#ENTRYPOINT ["sh", "setup.sh"]
