# Generated by Django 4.0.3 on 2022-04-03 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTrees',
            fields=[
                ('skill_tree_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('theme', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTreePaths',
            fields=[
                ('path_id', models.AutoField(primary_key=True, serialize=False)),
                ('starting_hex_q', models.IntegerField()),
                ('starting_hex_r', models.IntegerField()),
                ('starting_hex_s', models.IntegerField()),
                ('ending_hex_q', models.IntegerField()),
                ('ending_hex_r', models.IntegerField()),
                ('ending_hex_s', models.IntegerField()),
                ('starting_hex_string', models.CharField(max_length=11)),
                ('ending_hex_string', models.CharField(max_length=11)),
                ('skill_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltree.skilltrees')),
            ],
        ),
        migrations.CreateModel(
            name='SkillTreeHexagons',
            fields=[
                ('hex_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('hex_q', models.IntegerField()),
                ('hex_r', models.IntegerField()),
                ('hex_s', models.IntegerField()),
                ('allow_verbal_feedback', models.BooleanField(default=False)),
                ('allow_quantitative_feedback', models.BooleanField(default=False)),
                ('image_address', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=70)),
                ('hex_string', models.CharField(max_length=11)),
                ('skill_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltree.skilltrees')),
            ],
        ),
    ]
