# Generated by Django 4.0.3 on 2022-04-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltreehexagons',
            name='hex_string',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='skilltreepaths',
            name='ending_hex_string',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='skilltreepaths',
            name='starting_hex_string',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
