# Generated by Django 4.0.3 on 2022-03-27 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skilltree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltreehexagons',
            name='note_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skilltree.skilltreehexagonnotes'),
            preserve_default=False,
        ),
    ]
