# Generated by Django 4.0.3 on 2022-04-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltree', '0002_alter_skilltreehexagons_hex_string_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltreehexagons',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
