# Generated by Django 4.0.3 on 2022-03-27 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skilltree', '0002_skilltreehexagons_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltreehexagonnotes',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skilltreehexagons',
            name='image_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skilltreehexagons',
            name='note_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skilltree.skilltreehexagonnotes'),
        ),
    ]
