# Generated by Django 4.0.3 on 2022-04-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltree', '0003_alter_skilltreehexagons_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltreehexagons',
            name='allow_quantitative_feedback',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='skilltreehexagons',
            name='allow_verbal_feedback',
            field=models.BooleanField(default=True),
        ),
    ]
