# Generated by Django 4.0.3 on 2022-03-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltree', '0005_skilltrees_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltreehexagons',
            name='hex_string',
            field=models.CharField(default='1,1,1', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skilltreepaths',
            name='ending_hex_string',
            field=models.CharField(default='2,2,2', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skilltreepaths',
            name='starting_hex_string',
            field=models.CharField(default='1,1,1', max_length=11),
            preserve_default=False,
        ),
    ]
