# Generated by Django 4.0.3 on 2022-04-13 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skilltree', '0007_alter_skilltreehexagons_hex_string_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltrees',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
