# Generated by Django 4.0.4 on 2022-04-17 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skilltree', '0010_alter_skilltrees_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltreehexagons',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
