# Generated by Django 4.0.4 on 2022-05-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltree', '0012_rename_owner_skilltreehexagons_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTreeThemes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(default='default', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='skilltrees',
            name='theme',
        ),
    ]
