# Generated by Django 4.0.4 on 2022-05-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skilltree', '0013_skilltreethemes_remove_skilltrees_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltrees',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skilltree.skilltreethemes', to_field='theme'),
        ),
        migrations.AlterField(
            model_name='skilltreethemes',
            name='theme',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
