# Generated by Django 4.0.4 on 2022-05-02 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skilltree', '0014_skilltrees_theme_alter_skilltreethemes_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltrees',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skilltree.skilltreethemes', to_field='theme'),
        ),
    ]
